name: "Test Backend"
on: [push, pull_request]

jobs:
  test-backend:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.4.0
          cache: true
          cache-bin: true
      - name: Bun install
        working-directory: ./backend
        run: bun i
